name: brca-cd44-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Python
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter

  # R + DESeq2 ecosystem
  - r-base
  - r-essentials
  - r-deseq2
  - r-ggplot2
  - r-biocmanager

  # Python <-> R bridge
  - rpy2

  # for filesystem & tools
  - pip
